_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [39]:
import numpy as np

arr = np.array([10, 5, 7, 20, 15, -9, 33])
print("Array:", arr)
print("Maximum value:", np.max(arr))
print("Minimum value:", np.min(arr))

Array: [10  5  7 20 15 -9 33]
Maximum value: 33
Minimum value: -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [40]:
# Find the maximum value in arr without using max function
maximum = arr[0]
for num in arr:
    if num > maximum:
        maximum = num
print("Maximum value (without using max):", maximum)

Maximum value (without using max): 33


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [41]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 4], [6, 8]])

sum_matrix = matrix1 + matrix2
diff_matrix = matrix1 - matrix2

print("Sum of matrices:\n", sum_matrix)
print("Subtraction of matrices:\n", diff_matrix)

Sum of matrices:
 [[ 3  6]
 [ 9 12]]
Subtraction of matrices:
 [[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [42]:
# Generate a random matrix of size 5x6
random_matrix = np.random.rand(5, 6)

# Generate a new random row of size 6
new_row = np.random.rand(1, 6)

# Add the new row to the matrix
extended_matrix = np.vstack([random_matrix, new_row])

# Find the sum of each row
row_sums = np.sum(extended_matrix, axis=1)

print("Extended Matrix:\n", extended_matrix)
print("Sum of each row:", row_sums)

Extended Matrix:
 [[0.63055565 0.23179048 0.67545406 0.07855307 0.72789652 0.42765203]
 [0.86814356 0.54112143 0.25053449 0.83892312 0.21915204 0.53855323]
 [0.83655142 0.54791065 0.77076845 0.98440312 0.51345088 0.13376606]
 [0.8634713  0.77125431 0.41250454 0.88632974 0.60130397 0.94352305]
 [0.888954   0.88233146 0.80547256 0.41224332 0.14555411 0.76903054]
 [0.70466825 0.56516249 0.75687911 0.05209582 0.04843557 0.85408408]]
Sum of each row: [2.7719018  3.25642787 3.78685057 4.47838689 3.90358599 2.98132533]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [43]:
# Generate a random integer matrix of size 5x6
int_matrix = np.random.randint(low=0, high=100, size=(5, 6))

# Generate a new random integer column of size 5x1
new_col = np.random.randint(low=0, high=100, size=(5, 1))

# Add the new column to the matrix
extended_int_matrix = np.hstack([int_matrix, new_col])

# Compute the sine of each element
sine_matrix = np.sin(extended_int_matrix)

print("Extended Integer Matrix:\n", extended_int_matrix)
print("Sine of each element:\n", sine_matrix)

Extended Integer Matrix:
 [[ 8 48 52 36 66 50 69]
 [91 53 95 14 72 50 88]
 [48 77 39 32 22 62 42]
 [15 52 36 86 32 85 74]
 [33  8 79 90 87 79 21]]
Sine of each element:
 [[ 0.98935825 -0.76825466  0.98662759 -0.99177885 -0.02655115 -0.26237485
  -0.11478481]
 [ 0.10598751  0.39592515  0.68326171  0.99060736  0.25382336 -0.26237485
   0.0353983 ]
 [-0.76825466  0.99952016  0.96379539  0.55142668 -0.00885131 -0.7391807
  -0.91652155]
 [ 0.65028784  0.98662759 -0.99177885 -0.92345845  0.55142668 -0.17607562
  -0.98514626]
 [ 0.99991186  0.98935825 -0.44411267  0.89399666 -0.82181784 -0.44411267
   0.83665564]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [44]:
# Generate a random matrix of size 5x6
matrix = np.random.rand(5, 6)

# Select the 3rd and 4th row (index 2 and 3), and 2nd, 3rd, and 4th column (index 1, 2, 3)
sliced_matrix = matrix[2:4, 1:4]

print("Original Matrix:\n", matrix)
print("Sliced Matrix (3rd & 4th row, 2nd-4th column):\n", sliced_matrix)

Original Matrix:
 [[0.3324878  0.70611094 0.22592438 0.48355258 0.93174139 0.37460431]
 [0.34347692 0.84453381 0.92219713 0.54501896 0.22676662 0.93375259]
 [0.74201568 0.43156406 0.38739002 0.75961573 0.17143793 0.6248592 ]
 [0.51499695 0.37561536 0.76573015 0.17589942 0.61024385 0.8355761 ]
 [0.61115836 0.47553538 0.17964849 0.82225646 0.99119804 0.95871123]]
Sliced Matrix (3rd & 4th row, 2nd-4th column):
 [[0.43156406 0.38739002 0.75961573]
 [0.37561536 0.76573015 0.17589942]]


### Great Job!